import React, { useEffect, useState } from 'react';
import { Share, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';

type Verse={book:string;chapter:number;verse:number;text:string}; type Mark='yellow'|'green'|'blue'|'pink';
const books=['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalms','Proverbs','Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation'];
const counts=[50,40,27,36,34,24,21,4,31,24,22,25,29,36,10,13,10,42,150,31,12,8,66,52,5,48,12,14,3,9,1,4,7,3,3,3,2,14,4,28,16,24,21,28,16,13,6,6,4,4,5,3,5,1,13,5,5,3,1,13,5,5,1,1,1,1,22];
const C={navy:'#10263D',cream:'#F6F1E7',green:'#7BAE7F',muted:'#68747F'};
const key=(v:Verse)=>v.book+' '+v.chapter+':'+v.verse;
export function BibleReader({initial}:{initial:string}){const[reader,setReader]=useState(false),[query,setQuery]=useState(initial),[book,setBook]=useState('Psalms'),[chapter,setChapter]=useState(46),[verses,setVerses]=useState<Verse[]>([]),[results,setResults]=useState<Verse[]>([]),[selected,setSelected]=useState<Verse|null>(null),[marks,setMarks]=useState<Record<string,Mark>>({}),[saved,setSaved]=useState<Record<string,Verse>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[writing,setWriting]=useState(false),[draft,setDraft]=useState('');
 const open=async(value:string)=>{try{const r=await fetch('https://bible-api.com/'+encodeURIComponent(value)+'?translation=kjv'),j=await r.json();if(!r.ok)throw 0;const list=(j.verses||[]).map((v:any)=>({book:j.reference.replace(/ \d.*$/,''),chapter:v.chapter,verse:v.verse,text:v.text.trim()}));setVerses(list);setBook(list[0]?.book||book);setChapter(list[0]?.chapter||chapter);setResults([]);setSelected(null);setReader(true)}catch{setVerses([]);setReader(true)}};
 const search=async()=>{if(/\d/.test(query))return open(query);try{const r=await fetch('https://api.biblesupersearch.com/api?bible=kjv&search='+encodeURIComponent(query)),j=await r.json();setResults(j.results.slice(0,20).flatMap((x:any)=>Object.values(x.verses.kjv||{}).flatMap((c:any)=>Object.values(c).map((v:any)=>({book:x.book_name,chapter:v.chapter,verse:v.verse,text:v.text.trim()})))))}catch{setResults([])}};
 useEffect(()=>{void open(initial)},[]);
 const toggleSave=(v:Verse)=>setSaved(x=>{const n={...x};if(n[key(v)])delete n[key(v)];else n[key(v)]=v;return n});
 const chapterOpen=(n:number)=>open(book+' '+n);
 if(reader)return <ScrollView contentContainerStyle={s.reader}><View style={s.readerHead}><TouchableOpacity onPress={()=>setReader(false)}><Text style={s.back}>‹ Bible</Text></TouchableOpacity><View><Text style={s.kjv}>KJV</Text><Text style={s.heading}>{book} {chapter}</Text></View><TouchableOpacity onPress={()=>verses[0]&&toggleSave(verses[0])}><Text style={s.save}>{verses[0]&&saved[key(verses[0])]?'♥':'♡'}</Text></TouchableOpacity></View>{verses.map(v=><TouchableOpacity key={key(v)} onPress={()=>setSelected(v)} style={[s.verse,marks[key(v)]&&s[marks[key(v)]]]}><Text style={s.num}>{v.verse}</Text><Text style={s.scripture}>{v.text}</Text></TouchableOpacity>)}<View style={s.navrow}><Button label="Previous chapter" onPress={()=>chapter>1&&chapterOpen(chapter-1)}/><Button label="Next chapter" onPress={()=>chapter<counts[books.indexOf(book)]&&chapterOpen(chapter+1)}/></View>{selected&&<View style={s.actions}><Text style={s.actionRef}>{key(selected)}</Text><View style={s.actionRow}>{(['yellow','green','blue','pink']as Mark[]).map(m=><TouchableOpacity key={m} onPress={()=>setMarks(x=>({...x,[key(selected)]:m}))} style={[s.dot,s[m]]}/>)}</View><Button label={saved[key(selected)]?'Remove bookmark':'Favourite'} onPress={()=>toggleSave(selected)}/><Button label="Copy" onPress={()=>Clipboard.setStringAsync(selected.text+' — '+key(selected))}/><Button label="Share" onPress={()=>Share.share({message:selected.text+' — '+key(selected)+' KJV'})}/><Button label="Add note" onPress={()=>{setDraft(notes[key(selected)]||'');setWriting(true)}}/>{writing&&<><TextInput value={draft} onChangeText={setDraft} placeholder="Write a personal note…" multiline style={s.note}/><Button label="Save note" onPress={()=>{setNotes(x=>({...x,[key(selected)]:draft}));setWriting(false)}}/></>}</View>}</ScrollView>;
 return <ScrollView contentContainerStyle={s.home}><Text style={s.ey}>THE HOLY BIBLE · KJV</Text><Text style={s.title}>Read Scripture</Text><Text style={s.sub}>Search a passage or explore the complete King James Bible.</Text><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="John 3:16 or faith" style={s.input}/><Button label={/\d/.test(query)?'Open passage':'Search Scripture'} onPress={search}/><Text style={s.section}>Continue Reading</Text><TouchableOpacity style={s.card} onPress={()=>open(book+' '+chapter)}><Text style={s.cardTitle}>{book} {chapter}</Text><Text style={s.sub}>Return to your last passage</Text></TouchableOpacity><Text style={s.section}>Popular passages</Text><View style={s.chips}>{['Psalm 23','Psalm 46','John 3:16','Romans 8','Philippians 4','Matthew 6','1 Corinthians 13'].map(p=><TouchableOpacity key={p} onPress={()=>open(p)} style={s.chip}><Text>{p}</Text></TouchableOpacity>)}</View><Text style={s.section}>Browse Bible</Text><ScrollView horizontal contentContainerStyle={s.chips}>{books.map(b=><TouchableOpacity key={b} onPress={()=>{setBook(b);setChapter(1);open(b+' 1')}} style={s.chip}><Text>{b}</Text></TouchableOpacity>)}</ScrollView><Text style={s.section}>Saved Scripture</Text>{Object.values(saved).length?<>{Object.values(saved).map(v=><TouchableOpacity key={key(v)} onPress={()=>open(key(v))} style={s.card}><Text style={s.cardTitle}>♥ {key(v)}</Text><Text numberOfLines={1} style={s.sub}>{v.text}</Text></TouchableOpacity>)}</>:<Text style={s.sub}>Bookmark verses while you read to find them here.</Text>}{results.map(v=><TouchableOpacity key={key(v)} onPress={()=>open(key(v))} style={s.card}><Text style={s.ey}>{key(v)}</Text><Text style={s.result}>“{v.text}”</Text></TouchableOpacity>)}</ScrollView>}
function Button({label,onPress}:{label:string;onPress:()=>void}){return <TouchableOpacity onPress={onPress} style={s.button}><Text style={s.buttonText}>{label}</Text></TouchableOpacity>}
const s=StyleSheet.create({home:{padding:22,paddingBottom:40,backgroundColor:C.cream},reader:{padding:22,paddingBottom:50,backgroundColor:'#fff'},ey:{fontSize:10,fontWeight:'900',letterSpacing:1.6,color:C.green,marginBottom:7},title:{fontSize:34,fontWeight:'800',color:C.navy,marginBottom:8},sub:{fontSize:12,color:C.muted,lineHeight:18},input:{backgroundColor:'#fff',borderRadius:18,padding:15,fontSize:15,color:C.navy,marginTop:16},button:{backgroundColor:C.green,paddingHorizontal:15,paddingVertical:11,borderRadius:20,alignSelf:'flex-start',marginTop:12},buttonText:{fontWeight:'800',color:C.navy},section:{fontSize:20,fontWeight:'800',color:C.navy,marginTop:26,marginBottom:11},card:{backgroundColor:'#fff',padding:16,borderRadius:18,marginBottom:9},cardTitle:{fontSize:15,fontWeight:'800',color:C.navy,marginBottom:4},chips:{gap:8,paddingBottom:5},chip:{backgroundColor:'#fff',paddingVertical:9,paddingHorizontal:12,borderRadius:16},result:{fontFamily:'serif',fontSize:16,lineHeight:24,color:C.navy},readerHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#eee',paddingBottom:14,marginBottom:18},back:{fontWeight:'800',color:C.navy},kjv:{fontSize:9,fontWeight:'900',letterSpacing:1,color:C.green,textAlign:'center'},heading:{fontSize:19,fontWeight:'800',color:C.navy},save:{fontSize:28,color:C.navy},verse:{flexDirection:'row',paddingVertical:9,borderRadius:6},num:{width:27,color:C.green,fontWeight:'800',fontSize:11,paddingTop:4},scripture:{flex:1,fontFamily:'serif',fontSize:19,lineHeight:33,color:C.navy},yellow:{backgroundColor:'#fff2a8'},green:{backgroundColor:'#dcebdd'},blue:{backgroundColor:'#ddebff'},pink:{backgroundColor:'#ffe0e8'},navrow:{flexDirection:'row',justifyContent:'space-between',marginTop:18},actions:{backgroundColor:C.navy,borderRadius:20,padding:16,marginTop:20},actionRef:{color:'#fff',fontWeight:'800'},actionRow:{flexDirection:'row',gap:10,marginTop:10},dot:{width:28,height:28,borderRadius:14},note:{backgroundColor:'#fff',borderRadius:12,padding:10,minHeight:70,marginTop:12}});
