import React,{useState}from'react';
import{Linking,ScrollView,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import*as Clipboard from'expo-clipboard';
const site='https://www.calvarywaterford.com/';
const join=()=>Linking.openURL('https://wa.me/353860739394?text='+encodeURIComponent('Hi Dee, I’d like to join the Calvary Waterford WhatsApp Community.'));
const pages:any={
 'Our Story':{title:'Our Story',body:'Calvary Waterford started as a small Bible Study in a home in the Summer of 2008. Since then God has slowly but surely been building the church, moving us to a local hotel, then in to our own building at 59/60 Lower Yellow Road. We have always felt that God is calling us to be a local church in Waterford City Centre serving the city while communicating the message of peace, hope and truth that is found in the Word of God, the Bible.'},
 'Kids Ministry':{title:"Kid’s Church",body:'A safe, fun environment where children can learn more about God. A separate crèche area welcomes babies and toddlers aged 1–3. Kids Church has a classroom for children aged 3–12, with age-appropriate Bible teaching, games, songs, crafts and activities. More than a dozen volunteers, coordinated by Dee Keating, serve in the ministry; all are Garda Vetted. Parents are welcome to meet the teachers and see the facilities.'},
 'Women’s Ministry':{title:"Women’s Ministry",body:'Opportunities for women from the church and local area to connect, develop friendships and enjoy time together. Throughout the month there are book clubs, coffee mornings, social events and community outreach, alongside women’s gatherings through the year.'},
 'Men’s Ministry':{title:"Men’s Ministry",body:'Monthly meetups give men from the church and local community a chance to connect, build friendships and enjoy time together over food. From time to time the church also organises camping trips, hikes and barbecues.'},
 'Teens & Preteens':{title:'Teens & Preteens',body:'Alternating Fridays. A welcoming place for younger members of the church community. Message us for more details.'},
 'Home Groups':{title:'Home Groups',body:'Every Wednesday. Small groups are a place for fellowship, Bible study, prayer and growing together. Message us for more details.'},
 'Need Prayer?':{title:'Need Prayer?',body:'Calvary Waterford welcomes prayer requests. Send your request securely through the official church contact form.'},
 'Our Fundamentals':{title:'Our Fundamentals',body:'Jesus and His Word · faithful teaching of the Bible · prayer · fellowship (koinonia) · worship · serving the community and one another · reaching people with the Gospel.'},
 'What We Believe':{title:'What We Believe',body:'The Bible · God · Jesus Christ · Salvation · Holy Spirit · The Church · Eternity · Marriage & Sexuality · Our Distinctives · Gifts of the Holy Spirit · Church Leadership · Baptism · Return of Christ · Ministry Philosophy · Local Church Autonomy.'}
};
export function ChurchInfo(){const[p,setP]=useState('');if(p==='Giving')return <Giving back={()=>setP('')}/>;if(p==='Become a Member')return <Detail title="Become a Member" body="Use Calvary Waterford’s official form to get connected." back={()=>setP('')} action="Open membership form" url="https://docs.google.com/forms/d/e/1FAIpQLSfQiUziff-LLM2zQBkFw73mk3NQCr5AJVFhFybonAMfLvteNA/viewform?pli=1"/>;if(p==='Contact & Location')return <Detail title="Contact Calvary Waterford" body="59/60 Lower Yellow Road\nWaterford City\nIreland\n\nQuestions, prayer requests, and ways to get connected can be sent through the official church website." back={()=>setP('')} action="Open website contact form" url={site}/>;if(p&&pages[p])return <Detail {...pages[p]} back={()=>setP('')} action={p==='Home Groups'?'Join a Group on WhatsApp':p==='Need Prayer?'?'Send a Prayer Request':'Learn more on the church website'} url={p==='Home Groups'?undefined:site} onAction={p==='Home Groups'?join:undefined}/>;const section=(title:string,items:string[]) => <><Text style={s.ey}>{title}</Text>{items.map(x=><TouchableOpacity key={x} style={s.row} onPress={()=>setP(x)}><Text style={s.rowText}>{x}</Text><Text style={s.arrow}>›</Text></TouchableOpacity>)}</>;return <ScrollView contentContainerStyle={s.page}><Text style={s.ey}>GET CONNECTED</Text><View style={s.join}><Text style={s.joinTitle}>Calvary Waterford WhatsApp Community</Text><Text style={s.light}>Request to join and a church leader will approve your request.</Text><Button label="Join a Group on WhatsApp" onPress={join}/></View>{section('GET CONNECTED',['Become a Member','Home Groups','Kids Ministry','Teens & Preteens','Women’s Ministry','Men’s Ministry','Need Prayer?'])}{section('ABOUT CALVARY',['Our Story','What We Believe','Our Fundamentals','Contact & Location'])}{section('SUPPORT',['Giving'])}</ScrollView>}
function Detail({title,body,back,action,url,onAction}:{title:string;body:string;back:()=>void;action:string;url?:string;onAction?:()=>void}){return <ScrollView contentContainerStyle={s.page}><TouchableOpacity onPress={back}><Text style={s.back}>‹ More</Text></TouchableOpacity><Text style={s.ey}>CALVARY WATERFORD</Text><Text style={s.title}>{title}</Text><Text style={s.body}>{body}</Text><Button label={action} onPress={onAction||(()=>url&&Linking.openURL(url))}/></ScrollView>}
function Giving({back}:{back:()=>void}){const iban='IE06AIBK93427535485067';return <ScrollView contentContainerStyle={s.page}><TouchableOpacity onPress={back}><Text style={s.back}>‹ More</Text></TouchableOpacity><Text style={s.ey}>SUPPORT</Text><Text style={s.title}>Giving & Generosity</Text><Text style={s.body}>Your contribution supports Calvary Waterford’s work, discipleship, ministries, outreach and missions.</Text><View style={s.bank}><Text style={s.bankLabel}>AIB MAIN ACCOUNT</Text><Text style={s.rowText}>Account Name: Calvary Waterford</Text><Text selectable style={s.iban}>{iban}</Text><Button label="Copy IBAN" onPress={()=>Clipboard.setStringAsync(iban)}/></View><Button label="View Official Giving Page" onPress={()=>Linking.openURL(site+'giving')}/></ScrollView>}
function Button({label,onPress}:{label:string;onPress:()=>void}){return <TouchableOpacity style={s.button} onPress={onPress}><Text style={s.buttonText}>{label}</Text></TouchableOpacity>}
const s=StyleSheet.create({page:{padding:22,paddingBottom:45,backgroundColor:'#F6F1E7'},ey:{fontSize:10,fontWeight:'900',letterSpacing:1.6,color:'#7BAE7F',marginTop:8,marginBottom:9},title:{fontSize:33,fontWeight:'800',color:'#10263D',marginBottom:17},body:{fontSize:16,lineHeight:26,color:'#10263D'},join:{backgroundColor:'#091B2D',borderRadius:24,padding:21,marginBottom:25},joinTitle:{fontSize:20,fontWeight:'800',color:'#fff'},light:{color:'#d7e4e9',fontSize:12,lineHeight:18,marginTop:7},row:{backgroundColor:'#fff',borderRadius:18,padding:17,marginBottom:9,flexDirection:'row',alignItems:'center'},rowText:{flex:1,fontSize:16,fontWeight:'800',color:'#10263D'},arrow:{fontSize:26,color:'#68747F'},button:{alignSelf:'flex-start',backgroundColor:'#7BAE7F',borderRadius:21,paddingVertical:12,paddingHorizontal:16,marginTop:17},buttonText:{color:'#10263D',fontWeight:'900'},back:{color:'#10263D',fontWeight:'800',marginBottom:18},bank:{backgroundColor:'#fff',borderRadius:20,padding:18,marginTop:22},bankLabel:{fontSize:10,letterSpacing:1.4,fontWeight:'900',color:'#7BAE7F',marginBottom:9},iban:{fontSize:16,fontWeight:'800',color:'#10263D',marginTop:13}});
